// Code generated by "stringer -type=CompilationMode"; DO NOT EDIT.

package testcase

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReleaseMode-1]
	_ = x[AnalyzeClangMode-2]
	_ = x[AnalyzeGplusplusMode-3]
}

const _CompilationMode_name = "ReleaseModeAnalyzeClangModeAnalyzeGplusplusMode"

var _CompilationMode_index = [...]uint8{0, 11, 27, 47}

func (i CompilationMode) String() string {
	i -= 1
	if i < 0 || i >= CompilationMode(len(_CompilationMode_index)-1) {
		return "CompilationMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CompilationMode_name[_CompilationMode_index[i]:_CompilationMode_index[i+1]]
}
