// Code generated by "stringer -type=Status"; DO NOT EDIT.

package testcase

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotRunYet-0]
	_ = x[InternalError-1]
	_ = x[TimeLimitExceeded-2]
	_ = x[MemoryLimitExceeded-3]
	_ = x[WrongAnswer-4]
	_ = x[Accepted-5]
}

const _Status_name = "NotRunYetInternalErrorTimeLimitExceededMemoryLimitExceededWrongAnswerAccepted"

var _Status_index = [...]uint8{0, 9, 22, 39, 58, 69, 77}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
