// Code generated by "stringer -type=SubmissionState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Queued-0]
	_ = x[Compiling-1]
	_ = x[Processing-2]
	_ = x[Processed-3]
}

const _SubmissionState_name = "QueuedCompilingProcessingProcessed"

var _SubmissionState_index = [...]uint8{0, 6, 15, 25, 34}

func (i SubmissionState) String() string {
	if i < 0 || i >= SubmissionState(len(_SubmissionState_index)-1) {
		return "SubmissionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubmissionState_name[_SubmissionState_index[i]:_SubmissionState_index[i+1]]
}
