// Code generated by "stringer -type=TestCaseStatus"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotRunYet-0]
	_ = x[InternalError-1]
	_ = x[CompilationError-2]
	_ = x[TimeLimitExceeded-3]
	_ = x[MemoryLimitExceeded-4]
	_ = x[WrongAnswer-5]
	_ = x[Accepted-6]
}

const _TestCaseStatus_name = "NotRunYetInternalErrorCompilationErrorTimeLimitExceededMemoryLimitExceededWrongAnswerAccepted"

var _TestCaseStatus_index = [...]uint8{0, 9, 22, 38, 55, 74, 85, 93}

func (i TestCaseStatus) String() string {
	if i < 0 || i >= TestCaseStatus(len(_TestCaseStatus_index)-1) {
		return "TestCaseStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestCaseStatus_name[_TestCaseStatus_index[i]:_TestCaseStatus_index[i+1]]
}
